// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_summaries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConversationSummary = `-- name: DeleteConversationSummary :exec
DELETE FROM conversation_summaries
WHERE bot_id = $1 AND chat_id = $2
`

type DeleteConversationSummaryParams struct {
	BotID  pgtype.UUID `json:"bot_id"`
	ChatID string      `json:"chat_id"`
}

func (q *Queries) DeleteConversationSummary(ctx context.Context, arg DeleteConversationSummaryParams) error {
	_, err := q.db.Exec(ctx, deleteConversationSummary, arg.BotID, arg.ChatID)
	return err
}

const getConversationSummary = `-- name: GetConversationSummary :one
SELECT id, bot_id, chat_id, summary, message_count, created_at, updated_at FROM conversation_summaries
WHERE bot_id = $1 AND chat_id = $2
`

type GetConversationSummaryParams struct {
	BotID  pgtype.UUID `json:"bot_id"`
	ChatID string      `json:"chat_id"`
}

func (q *Queries) GetConversationSummary(ctx context.Context, arg GetConversationSummaryParams) (ConversationSummary, error) {
	row := q.db.QueryRow(ctx, getConversationSummary, arg.BotID, arg.ChatID)
	var i ConversationSummary
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.ChatID,
		&i.Summary,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConversationSummary = `-- name: UpsertConversationSummary :one
INSERT INTO conversation_summaries (bot_id, chat_id, summary, message_count)
VALUES ($1, $2, $3, $4)
ON CONFLICT (bot_id, chat_id) DO UPDATE
SET summary = EXCLUDED.summary,
    message_count = conversation_summaries.message_count + EXCLUDED.message_count,
    updated_at = now()
RETURNING id, bot_id, chat_id, summary, message_count, created_at, updated_at
`

type UpsertConversationSummaryParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	ChatID       string      `json:"chat_id"`
	Summary      string      `json:"summary"`
	MessageCount int32       `json:"message_count"`
}

func (q *Queries) UpsertConversationSummary(ctx context.Context, arg UpsertConversationSummaryParams) (ConversationSummary, error) {
	row := q.db.QueryRow(ctx, upsertConversationSummary,
		arg.BotID,
		arg.ChatID,
		arg.Summary,
		arg.MessageCount,
	)
	var i ConversationSummary
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.ChatID,
		&i.Summary,
		&i.MessageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
