// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: evolution_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeEvolutionLog = `-- name: CompleteEvolutionLog :one
UPDATE evolution_logs
SET status = $2,
    changes_summary = $3,
    files_modified = $4,
    agent_response = $5,
    completed_at = now()
WHERE id = $1
RETURNING id, bot_id, heartbeat_config_id, trigger_reason, status, changes_summary, files_modified, agent_response, started_at, completed_at, created_at
`

type CompleteEvolutionLogParams struct {
	ID             pgtype.UUID `json:"id"`
	Status         string      `json:"status"`
	ChangesSummary pgtype.Text `json:"changes_summary"`
	FilesModified  []string    `json:"files_modified"`
	AgentResponse  pgtype.Text `json:"agent_response"`
}

func (q *Queries) CompleteEvolutionLog(ctx context.Context, arg CompleteEvolutionLogParams) (EvolutionLog, error) {
	row := q.db.QueryRow(ctx, completeEvolutionLog,
		arg.ID,
		arg.Status,
		arg.ChangesSummary,
		arg.FilesModified,
		arg.AgentResponse,
	)
	var i EvolutionLog
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.HeartbeatConfigID,
		&i.TriggerReason,
		&i.Status,
		&i.ChangesSummary,
		&i.FilesModified,
		&i.AgentResponse,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countEvolutionLogsByBot = `-- name: CountEvolutionLogsByBot :one
SELECT count(*) FROM evolution_logs
WHERE bot_id = $1
`

func (q *Queries) CountEvolutionLogsByBot(ctx context.Context, botID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEvolutionLogsByBot, botID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvolutionLog = `-- name: CreateEvolutionLog :one
INSERT INTO evolution_logs (bot_id, heartbeat_config_id, trigger_reason, status)
VALUES ($1, $2, $3, 'running')
RETURNING id, bot_id, heartbeat_config_id, trigger_reason, status, changes_summary, files_modified, agent_response, started_at, completed_at, created_at
`

type CreateEvolutionLogParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	HeartbeatConfigID pgtype.UUID `json:"heartbeat_config_id"`
	TriggerReason     string      `json:"trigger_reason"`
}

func (q *Queries) CreateEvolutionLog(ctx context.Context, arg CreateEvolutionLogParams) (EvolutionLog, error) {
	row := q.db.QueryRow(ctx, createEvolutionLog, arg.BotID, arg.HeartbeatConfigID, arg.TriggerReason)
	var i EvolutionLog
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.HeartbeatConfigID,
		&i.TriggerReason,
		&i.Status,
		&i.ChangesSummary,
		&i.FilesModified,
		&i.AgentResponse,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEvolutionLog = `-- name: GetEvolutionLog :one
SELECT id, bot_id, heartbeat_config_id, trigger_reason, status, changes_summary, files_modified, agent_response, started_at, completed_at, created_at FROM evolution_logs
WHERE id = $1
`

func (q *Queries) GetEvolutionLog(ctx context.Context, id pgtype.UUID) (EvolutionLog, error) {
	row := q.db.QueryRow(ctx, getEvolutionLog, id)
	var i EvolutionLog
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.HeartbeatConfigID,
		&i.TriggerReason,
		&i.Status,
		&i.ChangesSummary,
		&i.FilesModified,
		&i.AgentResponse,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEvolutionLogsByBot = `-- name: ListEvolutionLogsByBot :many
SELECT id, bot_id, heartbeat_config_id, trigger_reason, status, changes_summary, files_modified, agent_response, started_at, completed_at, created_at FROM evolution_logs
WHERE bot_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEvolutionLogsByBotParams struct {
	BotID  pgtype.UUID `json:"bot_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListEvolutionLogsByBot(ctx context.Context, arg ListEvolutionLogsByBotParams) ([]EvolutionLog, error) {
	rows, err := q.db.Query(ctx, listEvolutionLogsByBot, arg.BotID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EvolutionLog
	for rows.Next() {
		var i EvolutionLog
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.HeartbeatConfigID,
			&i.TriggerReason,
			&i.Status,
			&i.ChangesSummary,
			&i.FilesModified,
			&i.AgentResponse,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
