// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: global_settings.sql

package sqlc

import (
	"context"
)

const getGlobalSetting = `-- name: GetGlobalSetting :one
SELECT key, value, updated_at FROM global_settings WHERE key = $1
`

func (q *Queries) GetGlobalSetting(ctx context.Context, key string) (GlobalSetting, error) {
	row := q.db.QueryRow(ctx, getGlobalSetting, key)
	var i GlobalSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const upsertGlobalSetting = `-- name: UpsertGlobalSetting :one
INSERT INTO global_settings (key, value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
RETURNING key, value, updated_at
`

type UpsertGlobalSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertGlobalSetting(ctx context.Context, arg UpsertGlobalSettingParams) (GlobalSetting, error) {
	row := q.db.QueryRow(ctx, upsertGlobalSetting, arg.Key, arg.Value)
	var i GlobalSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const listGlobalSettings = `-- name: ListGlobalSettings :many
SELECT key, value, updated_at FROM global_settings ORDER BY key
`

func (q *Queries) ListGlobalSettings(ctx context.Context) ([]GlobalSetting, error) {
	rows, err := q.db.Query(ctx, listGlobalSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalSetting
	for rows.Next() {
		var i GlobalSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
