// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: heartbeat_configs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHeartbeatConfig = `-- name: CreateHeartbeatConfig :one
INSERT INTO heartbeat_configs (bot_id, enabled, interval_seconds, prompt, event_triggers)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, bot_id, enabled, interval_seconds, prompt, event_triggers, created_at, updated_at
`

type CreateHeartbeatConfigParams struct {
	BotID           pgtype.UUID `json:"bot_id"`
	Enabled         bool        `json:"enabled"`
	IntervalSeconds int32       `json:"interval_seconds"`
	Prompt          string      `json:"prompt"`
	EventTriggers   []byte      `json:"event_triggers"`
}

func (q *Queries) CreateHeartbeatConfig(ctx context.Context, arg CreateHeartbeatConfigParams) (HeartbeatConfig, error) {
	row := q.db.QueryRow(ctx, createHeartbeatConfig,
		arg.BotID,
		arg.Enabled,
		arg.IntervalSeconds,
		arg.Prompt,
		arg.EventTriggers,
	)
	var i HeartbeatConfig
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.Prompt,
		&i.EventTriggers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHeartbeatConfig = `-- name: DeleteHeartbeatConfig :exec
DELETE FROM heartbeat_configs WHERE id = $1
`

func (q *Queries) DeleteHeartbeatConfig(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHeartbeatConfig, id)
	return err
}

const getHeartbeatConfig = `-- name: GetHeartbeatConfig :one
SELECT id, bot_id, enabled, interval_seconds, prompt, event_triggers, created_at, updated_at FROM heartbeat_configs WHERE id = $1
`

func (q *Queries) GetHeartbeatConfig(ctx context.Context, id pgtype.UUID) (HeartbeatConfig, error) {
	row := q.db.QueryRow(ctx, getHeartbeatConfig, id)
	var i HeartbeatConfig
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.Prompt,
		&i.EventTriggers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledHeartbeatConfigs = `-- name: ListEnabledHeartbeatConfigs :many
SELECT id, bot_id, enabled, interval_seconds, prompt, event_triggers, created_at, updated_at FROM heartbeat_configs WHERE enabled = true ORDER BY created_at
`

func (q *Queries) ListEnabledHeartbeatConfigs(ctx context.Context) ([]HeartbeatConfig, error) {
	rows, err := q.db.Query(ctx, listEnabledHeartbeatConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeartbeatConfig
	for rows.Next() {
		var i HeartbeatConfig
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Enabled,
			&i.IntervalSeconds,
			&i.Prompt,
			&i.EventTriggers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartbeatConfigsByBot = `-- name: ListHeartbeatConfigsByBot :many
SELECT id, bot_id, enabled, interval_seconds, prompt, event_triggers, created_at, updated_at FROM heartbeat_configs WHERE bot_id = $1 ORDER BY created_at
`

func (q *Queries) ListHeartbeatConfigsByBot(ctx context.Context, botID pgtype.UUID) ([]HeartbeatConfig, error) {
	rows, err := q.db.Query(ctx, listHeartbeatConfigsByBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HeartbeatConfig
	for rows.Next() {
		var i HeartbeatConfig
		if err := rows.Scan(
			&i.ID,
			&i.BotID,
			&i.Enabled,
			&i.IntervalSeconds,
			&i.Prompt,
			&i.EventTriggers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHeartbeatConfig = `-- name: UpdateHeartbeatConfig :one
UPDATE heartbeat_configs
SET enabled = $2,
    interval_seconds = $3,
    prompt = $4,
    event_triggers = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, bot_id, enabled, interval_seconds, prompt, event_triggers, created_at, updated_at
`

type UpdateHeartbeatConfigParams struct {
	ID              pgtype.UUID `json:"id"`
	Enabled         bool        `json:"enabled"`
	IntervalSeconds int32       `json:"interval_seconds"`
	Prompt          string      `json:"prompt"`
	EventTriggers   []byte      `json:"event_triggers"`
}

func (q *Queries) UpdateHeartbeatConfig(ctx context.Context, arg UpdateHeartbeatConfigParams) (HeartbeatConfig, error) {
	row := q.db.QueryRow(ctx, updateHeartbeatConfig,
		arg.ID,
		arg.Enabled,
		arg.IntervalSeconds,
		arg.Prompt,
		arg.EventTriggers,
	)
	var i HeartbeatConfig
	err := row.Scan(
		&i.ID,
		&i.BotID,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.Prompt,
		&i.EventTriggers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
