// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bm25Stat struct {
	Lang      string             `json:"lang"`
	DocCount  int32              `json:"doc_count"`
	AvgDocLen float64            `json:"avg_doc_len"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Bot struct {
	ID                  pgtype.UUID        `json:"id"`
	OwnerUserID         pgtype.UUID        `json:"owner_user_id"`
	Type                string             `json:"type"`
	DisplayName         pgtype.Text        `json:"display_name"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	IsActive            bool               `json:"is_active"`
	Status              string             `json:"status"`
	MaxContextLoadTime  int32              `json:"max_context_load_time"`
	Language            string             `json:"language"`
	AllowGuest          bool               `json:"allow_guest"`
	ChatModelID         pgtype.UUID        `json:"chat_model_id"`
	MemoryModelID       pgtype.UUID        `json:"memory_model_id"`
	EmbeddingModelID    pgtype.UUID        `json:"embedding_model_id"`
	VlmModelID          pgtype.UUID        `json:"vlm_model_id"`
	BackgroundModelID   pgtype.UUID        `json:"background_model_id"`
	ImageModelID        pgtype.UUID        `json:"image_model_id"`
	SearchProviderID    pgtype.UUID        `json:"search_provider_id"`
	Identity            pgtype.Text        `json:"identity"`
	Soul                pgtype.Text        `json:"soul"`
	Task                pgtype.Text        `json:"task"`
	AllowSelfEvolution  bool               `json:"allow_self_evolution"`
	EnableOpenviking    bool               `json:"enable_openviking"`
	IsPrivileged        bool               `json:"is_privileged"`
	GroupRequireMention bool               `json:"group_require_mention"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type BotCallLog struct {
	ID          pgtype.UUID        `json:"id"`
	CallerBotID pgtype.UUID        `json:"caller_bot_id"`
	TargetBotID pgtype.UUID        `json:"target_bot_id"`
	Message     string             `json:"message"`
	Result      pgtype.Text        `json:"result"`
	Status      string             `json:"status"`
	CallDepth   int32              `json:"call_depth"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type BotChannelConfig struct {
	ID               pgtype.UUID        `json:"id"`
	BotID            pgtype.UUID        `json:"bot_id"`
	ChannelType      string             `json:"channel_type"`
	Credentials      []byte             `json:"credentials"`
	ExternalIdentity pgtype.Text        `json:"external_identity"`
	SelfIdentity     []byte             `json:"self_identity"`
	Routing          []byte             `json:"routing"`
	Capabilities     []byte             `json:"capabilities"`
	Status           string             `json:"status"`
	VerifiedAt       pgtype.Timestamptz `json:"verified_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type BotChannelRoute struct {
	ID                     pgtype.UUID        `json:"id"`
	BotID                  pgtype.UUID        `json:"bot_id"`
	ChannelType            string             `json:"channel_type"`
	ChannelConfigID        pgtype.UUID        `json:"channel_config_id"`
	ExternalConversationID string             `json:"external_conversation_id"`
	ExternalThreadID       pgtype.Text        `json:"external_thread_id"`
	ConversationType       pgtype.Text        `json:"conversation_type"`
	DefaultReplyTarget     pgtype.Text        `json:"default_reply_target"`
	Metadata               []byte             `json:"metadata"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type BotHistoryMessage struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	RouteID                 pgtype.UUID        `json:"route_id"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	SenderAccountUserID     pgtype.UUID        `json:"sender_account_user_id"`
	ChannelType             pgtype.Text        `json:"channel_type"`
	SourceMessageID         pgtype.Text        `json:"source_message_id"`
	SourceReplyToMessageID  pgtype.Text        `json:"source_reply_to_message_id"`
	Role                    string             `json:"role"`
	Content                 []byte             `json:"content"`
	Metadata                []byte             `json:"metadata"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type BotMember struct {
	BotID     pgtype.UUID        `json:"bot_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BotPreauthKey struct {
	ID             pgtype.UUID        `json:"id"`
	BotID          pgtype.UUID        `json:"bot_id"`
	Token          string             `json:"token"`
	IssuedByUserID pgtype.UUID        `json:"issued_by_user_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	UsedAt         pgtype.Timestamptz `json:"used_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type BotTeam struct {
	ID           pgtype.UUID        `json:"id"`
	OwnerUserID  pgtype.UUID        `json:"owner_user_id"`
	Name         string             `json:"name"`
	ManagerBotID pgtype.UUID        `json:"manager_bot_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type BotTeamMember struct {
	ID              pgtype.UUID        `json:"id"`
	TeamID          pgtype.UUID        `json:"team_id"`
	SourceBotID     pgtype.UUID        `json:"source_bot_id"`
	TargetBotID     pgtype.UUID        `json:"target_bot_id"`
	RoleDescription string             `json:"role_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type BuiltinToolConfig struct {
	ID        pgtype.UUID        `json:"id"`
	BotID     pgtype.UUID        `json:"bot_id"`
	ToolName  string             `json:"tool_name"`
	Enabled   bool               `json:"enabled"`
	Priority  int32              `json:"priority"`
	Category  string             `json:"category"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Tier      string             `json:"tier"`
}

type ChannelIdentity struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	ChannelType      string             `json:"channel_type"`
	ChannelSubjectID string             `json:"channel_subject_id"`
	DisplayName      pgtype.Text        `json:"display_name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ChannelIdentityBindCode struct {
	ID                      pgtype.UUID        `json:"id"`
	Token                   string             `json:"token"`
	IssuedByUserID          pgtype.UUID        `json:"issued_by_user_id"`
	ChannelType             pgtype.Text        `json:"channel_type"`
	ExpiresAt               pgtype.Timestamptz `json:"expires_at"`
	UsedAt                  pgtype.Timestamptz `json:"used_at"`
	UsedByChannelIdentityID pgtype.UUID        `json:"used_by_channel_identity_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type Container struct {
	ID            pgtype.UUID        `json:"id"`
	BotID         pgtype.UUID        `json:"bot_id"`
	ContainerID   string             `json:"container_id"`
	ContainerName string             `json:"container_name"`
	Image         string             `json:"image"`
	Status        string             `json:"status"`
	Namespace     string             `json:"namespace"`
	AutoStart     bool               `json:"auto_start"`
	HostPath      pgtype.Text        `json:"host_path"`
	ContainerPath string             `json:"container_path"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LastStartedAt pgtype.Timestamptz `json:"last_started_at"`
	LastStoppedAt pgtype.Timestamptz `json:"last_stopped_at"`
}

type ContainerVersion struct {
	ID          string             `json:"id"`
	ContainerID string             `json:"container_id"`
	SnapshotID  string             `json:"snapshot_id"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ConversationSummary struct {
	ID           pgtype.UUID        `json:"id"`
	BotID        pgtype.UUID        `json:"bot_id"`
	ChatID       string             `json:"chat_id"`
	Summary      string             `json:"summary"`
	MessageCount int32              `json:"message_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EmbeddingCache struct {
	ID        pgtype.UUID `json:"id"`
	Provider  string      `json:"provider"`
	Model     string      `json:"model"`
	Hash      string      `json:"hash"`
	Embedding []byte      `json:"embedding"`
	Dims      int32       `json:"dims"`
	UpdatedAt int64       `json:"updated_at"`
	ExpiresAt int64       `json:"expires_at"`
}

type EvolutionLog struct {
	ID                pgtype.UUID        `json:"id"`
	BotID             pgtype.UUID        `json:"bot_id"`
	HeartbeatConfigID pgtype.UUID        `json:"heartbeat_config_id"`
	TriggerReason     string             `json:"trigger_reason"`
	Status            string             `json:"status"`
	ChangesSummary    pgtype.Text        `json:"changes_summary"`
	FilesModified     []string           `json:"files_modified"`
	FilesSnapshot     []byte             `json:"files_snapshot"`
	AgentResponse     pgtype.Text        `json:"agent_response"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type GlobalSetting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type HeartbeatConfig struct {
	ID              pgtype.UUID `json:"id"`
	BotID           pgtype.UUID `json:"bot_id"`
	Enabled         bool        `json:"enabled"`
	IntervalSeconds int32       `json:"interval_seconds"`
	Prompt          string      `json:"prompt"`
	EventTriggers   []byte      `json:"event_triggers"`
	// 0-23: hour of day (inclusive) at which heartbeat becomes active
	ActiveHoursStart int16 `json:"active_hours_start"`
	// 0-23: hour of day (inclusive) at which heartbeat stops firing
	ActiveHoursEnd int16 `json:"active_hours_end"`
	// ISO weekday numbers (0=Sunday … 6=Saturday) on which the heartbeat is active
	ActiveDays []int16            `json:"active_days"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type LifecycleEvent struct {
	ID          string             `json:"id"`
	ContainerID string             `json:"container_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type LlmProvider struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	ClientType string             `json:"client_type"`
	BaseUrl    string             `json:"base_url"`
	ApiKey     string             `json:"api_key"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type McpConnection struct {
	ID        pgtype.UUID        `json:"id"`
	BotID     pgtype.UUID        `json:"bot_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Config    []byte             `json:"config"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Model struct {
	ID              pgtype.UUID        `json:"id"`
	ModelID         string             `json:"model_id"`
	Name            pgtype.Text        `json:"name"`
	LlmProviderID   pgtype.UUID        `json:"llm_provider_id"`
	Dimensions      pgtype.Int4        `json:"dimensions"`
	IsMultimodal    bool               `json:"is_multimodal"`
	Type            string             `json:"type"`
	ContextWindow   int32              `json:"context_window"`
	FallbackModelID pgtype.UUID        `json:"fallback_model_id"`
	Reasoning       bool               `json:"reasoning"`
	MaxTokens       int32              `json:"max_tokens"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ModelVariant struct {
	ID        pgtype.UUID        `json:"id"`
	ModelUuid pgtype.UUID        `json:"model_uuid"`
	VariantID string             `json:"variant_id"`
	Weight    int32              `json:"weight"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProcessLog struct {
	ID         pgtype.UUID        `json:"id"`
	BotID      pgtype.UUID        `json:"bot_id"`
	ChatID     pgtype.UUID        `json:"chat_id"`
	TraceID    pgtype.UUID        `json:"trace_id"`
	UserID     pgtype.Text        `json:"user_id"`
	Channel    pgtype.Text        `json:"channel"`
	Step       interface{}        `json:"step"`
	Level      interface{}        `json:"level"`
	Message    pgtype.Text        `json:"message"`
	Data       []byte             `json:"data"`
	DurationMs pgtype.Int4        `json:"duration_ms"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Schedule struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Description  string             `json:"description"`
	Pattern      string             `json:"pattern"`
	MaxCalls     pgtype.Int4        `json:"max_calls"`
	CurrentCalls int32              `json:"current_calls"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Enabled      bool               `json:"enabled"`
	Command      string             `json:"command"`
	BotID        pgtype.UUID        `json:"bot_id"`
	Platform     string             `json:"platform"`
	ReplyTarget  string             `json:"reply_target"`
}

type SearchProvider struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Provider  string             `json:"provider"`
	Config    []byte             `json:"config"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Snapshot struct {
	ID               string             `json:"id"`
	ContainerID      string             `json:"container_id"`
	ParentSnapshotID pgtype.Text        `json:"parent_snapshot_id"`
	Snapshotter      string             `json:"snapshotter"`
	Digest           pgtype.Text        `json:"digest"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Subagent struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Deleted     bool               `json:"deleted"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	BotID       pgtype.UUID        `json:"bot_id"`
	Messages    []byte             `json:"messages"`
	Metadata    []byte             `json:"metadata"`
	Skills      []byte             `json:"skills"`
}

type SubagentRun struct {
	ID            pgtype.UUID        `json:"id"`
	RunID         string             `json:"run_id"`
	BotID         string             `json:"bot_id"`
	Name          string             `json:"name"`
	Task          string             `json:"task"`
	Status        string             `json:"status"`
	SpawnDepth    int32              `json:"spawn_depth"`
	ParentRunID   pgtype.Text        `json:"parent_run_id"`
	ResultSummary pgtype.Text        `json:"result_summary"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type TokenUsage struct {
	ID               pgtype.UUID        `json:"id"`
	BotID            pgtype.UUID        `json:"bot_id"`
	PromptTokens     int32              `json:"prompt_tokens"`
	CompletionTokens int32              `json:"completion_tokens"`
	TotalTokens      int32              `json:"total_tokens"`
	Model            string             `json:"model"`
	Source           string             `json:"source"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     pgtype.Text        `json:"username"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Role         string             `json:"role"`
	DisplayName  pgtype.Text        `json:"display_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	DataRoot     pgtype.Text        `json:"data_root"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	IsActive     bool               `json:"is_active"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserChannelBinding struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ChannelType string             `json:"channel_type"`
	Config      []byte             `json:"config"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
